name: Push to Docker Hub
uses: docker/build-push-action@v2
with:
  context: .
  file: ./Dockerfile
  push: true
  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sparcs-ci-test:latest
  username: ${{ secrets.DOCKER_HUB_USERNAME }}
  password: ${{ secrets.DOCKER_HUB_PASSWORD }}