name: Push to Docker Hub
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sparcs-cicd-test:latest
  pull_from_registry:
    name: Pull from Docker Hub and Run
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Login to Docker Hub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVKEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/sparcs-cicd-test:latest
            sudo docker run --name cicd-test -p 3001:3001 ${{ secrets.DOCKER_HUB_USERNAME }}/sparcs-cicd-test:latest
            sudo docker rmi $(docker images -f "dangling=true" -q)