name: Autorun at Docker Hub Push
on: [push, pull_request]

jobs:
  pull_from_registry:
    name: Pull from Docker Hub and Run
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Login to Docker Hub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVKEY }}
          script: |
            docker pull sparcs-cicd-test:latest
            docker run --name cicd-test -p 3001:3001 sparcs-cicd-test:latest
            docker rmi $(docker images -f "dangling=true" -q)